### ISSUE TITLE
Missing top border when option is toggled

### ISSUE THREAD

**Issue by y0nei** [neuromagus/disable_titlebar_in_sway#1]
## Issue
While the current implementation works fine, the way sway renders border ultimately makes the top one disappear when no titlebar is rendered.

## Possible fix
While I'm not a C dev I can hint on checking if its possible to achieve a proper result by making sway not render anything in the titlebar? Similarly to how [the workaround](https://github.com/swaywm/sway/issues/7409) worked

**Comment by neuromagus** [comment]
Thanks for your feedback. I work without any borders in monocle (tabbed) mode. I fix this stuff.

**Comment by neuromagus** [comment]
I changed archive to a new version of patch. If you have a time for testing, I will be glad. 

The instructions are the same.
