### ISSUE TITLE
Alternative ways to display list of windows in workplace

### ISSUE THREAD

**Issue by nnmmaaoo** [neuromagus/disable_titlebar_in_sway#2]
This is not a bug.
Default titlebar is ugly and takes place outside of the "bar", but it serves a purpose of listing windows, that are open in the workplace. Are there any options to get a similar functionality from "bars", like waybar? sway/window module shows only the current window title.

**Comment by nnmmaaoo** [comment]
Also thank you for this patch, very cool.

**Comment by neuromagus** [comment]
>Are there any options to get a similar functionality from "bars", like waybar?

IDK, but I did not touch this functionality.

**Comment by neuromagus** [comment]
P.S. I haven't used any panels and suggest you manage windows using hotkey combinations. I prefer monocle mode (for open my any programs in fullscreen) and switch windows by meta+S/D (QWERTY, I prefer my layout - [Dvorak](https://github.com/neuromagus/dvorak-improved). Or  1 workspace in tiled mode, 2 - fullscreen FF, 3 - fullscreen editor and 1-2 in bg terminals...

```<True way ;}>```
And about panels - use Dunst/Fnott/Mako etc with show delay 3sec and scripts for show any info's. For example -
```bash
#!/bin/sh
# time
notify-send "`date "+%H:%M %A%n%d %B"`"`
----------------------------------------
#!/bin/sh
# show Fan and CPU
notify-send "`sensors -A thinkpad-isa-0000  coretemp-isa-0000 | awk 'NR == 2 || NR == 11 || NR == 14 || NR == 15{print $1,$2,$3}'`"
---------------------------
#weather
#!/bin/sh
notify-send -t 4000 "`curl -s wttr.in/Moscow?format="%c++%t\nHumidity:+++%h\nMoon+phase:++%m\n"`"
```

```</True way>```

![20240514_16h16m18s_grim](https://github.com/neuromagus/disable_titlebar_in_sway/assets/63796667/fe5ee15c-c3ed-45ca-97fe-2a718446db5a)

**Comment by nnmmaaoo** [comment]
Oh ok, i understand. And i do manage windows almost exactly like that - its just i like seeing the list of opened windows on the bar so i dont have to remember what i have open. I guess using swayr  switch-window is an option ill go with.

**Comment by neuromagus** [comment]
good luck.

>its just i like seeing the list of opened windows on the bar so i dont have to remember what i have open. 

If we look at any professional workaround, we only see 4-6 programs for all things. Terminal emu (foot), Browser (FF/Chrome/Edge etc), Editor/viewer (imv/zathura etc), video/audio players (cmus/mpv etc) and, maybe, some messengers. That's all ;} Try to set this:

```
assign [app_id="transmission"] workspace number 1
assign [app_id="firefox"] workspace number 2
assign [app_id="chromium"] workspace number 2
assign [app_id="code"] workspace number 3
assign [app_id="emacs"] workspace number 3
assign [app_id="org.pwmt.zathura"] workspace number 4
assign [app_id="steam"] workspace number 5
```
and you always know where your program is ;}}}

P.S. True hackers (really :}) use NNN for [file manager](https://github.com/jarun/nnn) 💯
